# Generated by Django 5.1.3 on 2024-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
