# Generated by Django 5.1.3 on 2024-12-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
