# Generated by Django 5.1.3 on 2024-12-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_alter_customuser_managers_customuser_is_flag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
