# Generated by Django 5.1.3 on 2024-12-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_flag',
        ),
    ]
